### PR TITLE
Add a CodeCarbon exercice.

### PR DESCRIPTION
**Pull request by esclapez**
- [x] Test on Linux
- [ ] Test on MacOS + Intel CPU
- [ ] Test on Windows
- [x] Add conclusion/wrap-up

Address issue #26

### CODE REVIEW

**Comment by raar1** [comment]
This looks great Lucas, I will test on Linux now

**Review by raar1 — COMMENTED** [review]
OK, this is really nice. I just tested it on my laptop (running Ubuntu 24.04) and it seems to work. I do, however, get some warnings that other participants might get:

```
[codecarbon INFO @ 13:50:33] offline tracker init
[codecarbon INFO @ 13:50:33] [setup] RAM Tracking...
[codecarbon INFO @ 13:50:33] [setup] GPU Tracking...
[codecarbon INFO @ 13:50:33] No GPU found.
[codecarbon INFO @ 13:50:33] [setup] CPU Tracking...
[codecarbon WARNING @ 13:50:33] No CPU tracking mode found. Falling back on CPU constant mode. 
 Linux OS detected: Please ensure RAPL files exist at \sys\class\powercap\intel-rapl to measure CPU

[codecarbon WARNING @ 13:50:35] We saw that you have a 12th Gen Intel(R) Core(TM) i7-1250U but we don't know it. Please contact us.
[codecarbon INFO @ 13:50:35] CPU Model on constant consumption mode: 12th Gen Intel(R) Core(TM) i7-1250U
```

Although after this it does still measure and report energy consumption as expected (I think).

So I think we can tick the "test on Linux" one for now. Hopefully @JaroCamphuijsen can also try on his laptop to get a bit more confirmation.

I think we can find someone else in the centre to test on Windows? Maybe Walter? We may need to add a prerequisite for this course that Windows users have WSL installed or something like that to make this easier.

**Comment by raar1** [comment]
@esclapez I'm wondering if this is sufficiently done that we can merge it (I think we've tested it on Linux and Mac (arm?) so far. Could we make the Windows and Mac (intel) testing into issues that we can work on next week?

**Comment by esclapez** [comment]
@raar1 Yes, let's do that. I've added a few things, addressing the issue you raised regarding warnings.

**Pull request merged**
